package io.kestra.plugin.mistral;

import java.io.IOException;
import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeoutException;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.runners.RunContext;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.experimental.SuperBuilder;

@SuperBuilder
@Getter
@NoArgsConstructor
@ToString
@EqualsAndHashCode(callSuper = true)
@Plugin(
    examples = {
        @Example(
            title = "Run a Mistral Workflow and wait for completion",
            full = true,
            code = """
                id: mistral_run_workflow
                namespace: company.team

                tasks:
                  - id: run_workflow
                    type: io.kestra.plugin.mistral.RunWorkflow
                    apiKey: "{{ secret('MISTRAL_API_KEY') }}"
                    workflowIdentifier: "my-summarization-workflow"
                    input:
                      text: "Kestra is an open-source orchestration platform."
                      language: "en"
                    wait: true
                    waitTimeout: PT15M
                    pollInterval: PT5S
                """
        ),
        @Example(
            title = "Fire-and-forget a Mistral Workflow execution",
            full = true,
            code = """
                id: mistral_fire_and_forget
                namespace: company.team

                tasks:
                  - id: start_workflow
                    type: io.kestra.plugin.mistral.RunWorkflow
                    apiKey: "{{ secret('MISTRAL_API_KEY') }}"
                    workflowIdentifier: "my-long-running-workflow"
                    input:
                      dataset: "kestra://namespace/files/data.csv"
                    wait: false
                """
        )
    }
)
@Schema(
    title = "Run a Mistral Workflow execution",
    description = """
        Starts a Mistral Workflow execution via the REST API and optionally waits for it to reach a terminal state.

        **Note:** Mistral Workflows is currently in public preview. Register workflows via the Mistral Python SDK or Studio before using this task.

        When `wait` is `true` (default), the task polls every `pollInterval` until the execution completes, fails, or `waitTimeout` is reached.
        For long-running workflows (over 15 minutes), set `wait: false` and use the `WorkflowEvents` trigger to react to completion.

        Terminal success statuses: `COMPLETED`, `CANCELED`, `CONTINUED_AS_NEW`.
        Terminal failure statuses: `FAILED`, `TIMED_OUT`, `TERMINATED` — these cause the task to throw an exception.
        """
)
public class RunWorkflow extends AbstractMistralConnection implements RunnableTask<RunWorkflow.Output> {

    private static final Set<String> RUNNING_STATUSES = Set.of("RUNNING", "RETRYING_AFTER_ERROR");
    private static final Set<String> FAILURE_STATUSES = Set.of("FAILED", "TIMED_OUT", "TERMINATED");
    private static final ObjectMapper MAPPER = new ObjectMapper();

    @Schema(title = "Workflow identifier", description = "The name or ID of the registered Mistral workflow to execute.")
    @NotNull
    @PluginProperty(group = "main")
    private Property<String> workflowIdentifier;

    @Schema(title = "Input", description = "Key-value input map passed to the workflow on execution.")
    @PluginProperty(group = "main")
    private Property<Map<String, Object>> input;

    @Schema(title = "Deployment name", description = "Optional deployment name for routing to a specific workflow version.")
    @PluginProperty(group = "advanced")
    private Property<String> deploymentName;

    @Schema(title = "Execution ID", description = "Optional custom execution ID; a UUID is generated by the API when omitted.")
    @PluginProperty(group = "advanced")
    private Property<String> executionId;

    @Schema(title = "Wait for completion", description = "When `true`, the task polls until the execution reaches a terminal state. Defaults to `true`.")
    @Builder.Default
    @PluginProperty(group = "reliability")
    private Property<Boolean> wait = Property.ofValue(true);

    @Schema(title = "Wait timeout", description = "Maximum duration to wait for a terminal state before throwing a TimeoutException. Defaults to `PT15M`.")
    @Builder.Default
    @PluginProperty(group = "reliability")
    private Property<Duration> waitTimeout = Property.ofValue(Duration.ofMinutes(15));

    @Schema(title = "Poll interval", description = "How often to poll the execution status when `wait` is `true`. Defaults to `PT5S`.")
    @Builder.Default
    @PluginProperty(group = "reliability")
    private Property<Duration> pollInterval = Property.ofValue(Duration.ofSeconds(5));

    @Override
    public Output run(RunContext runContext) throws Exception {
        var rWorkflowIdentifier = runContext.render(workflowIdentifier).as(String.class).orElseThrow();
        var rInput = runContext.render(input).asMap(String.class, Object.class);
        var rDeploymentName = runContext.render(deploymentName).as(String.class).orElse(null);
        var rExecutionId = runContext.render(executionId).as(String.class).orElse(null);
        var rWait = runContext.render(wait).as(Boolean.class).orElse(true);
        var rWaitTimeout = runContext.render(waitTimeout).as(Duration.class).orElse(Duration.ofMinutes(15));
        var rPollInterval = runContext.render(pollInterval).as(Duration.class).orElse(Duration.ofSeconds(5));

        var requestBody = MAPPER.createObjectNode();
        requestBody.set("input", MAPPER.valueToTree(rInput));
        requestBody.put("wait_for_result", false);
        if (rDeploymentName != null) {
            requestBody.put("deployment_name", rDeploymentName);
        }
        if (rExecutionId != null) {
            requestBody.put("execution_id", rExecutionId);
        }

        var startResponse = executeRequest(runContext, "POST", "/workflows/" + rWorkflowIdentifier + "/execute", requestBody);
        var execId = startResponse.path("execution_id").asText();

        runContext.logger().info("Started Mistral workflow execution '{}' (workflow: {})", execId, rWorkflowIdentifier);

        if (!rWait) {
            return Output.builder()
                .executionId(execId)
                .status("RUNNING")
                .build();
        }

        return pollUntilTerminal(runContext, execId, rWaitTimeout, rPollInterval);
    }

    private Output pollUntilTerminal(RunContext runContext, String execId, Duration timeout, Duration interval) throws Exception {
        var deadline = Instant.now().plus(timeout);

        while (true) {
            var statusResponse = executeRequest(runContext, "GET", "/workflows/executions/" + execId, null);
            var status = statusResponse.path("status").asText();

            if (!RUNNING_STATUSES.contains(status)) {
                if (FAILURE_STATUSES.contains(status)) {
                    var message = statusResponse.path("error").asText(status);
                    throw new IOException("Mistral workflow execution '" + execId + "' ended with status " + status + ": " + message);
                }
                return buildOutput(execId, status, statusResponse);
            }

            if (Instant.now().isAfter(deadline)) {
                throw new TimeoutException("Mistral workflow execution '" + execId + "' did not reach a terminal state within " + timeout);
            }

            runContext.logger().debug("Execution '{}' status: {} — waiting {}s", execId, status, interval.getSeconds());
            Thread.sleep(interval.toMillis());
        }
    }

    private static Output buildOutput(String execId, String status, ObjectNode response) {
        var resultNode = response.path("result");
        var result = resultNode.isMissingNode() || resultNode.isNull() ? null : resultNode.toString();

        Long totalDurationMs = null;
        var startTime = response.path("start_time").asText(null);
        var endTime = response.path("end_time").asText(null);
        if (startTime != null && endTime != null) {
            try {
                totalDurationMs = Instant.parse(endTime).toEpochMilli() - Instant.parse(startTime).toEpochMilli();
            } catch (Exception ignored) {
                // non-ISO timestamps are ignored; totalDurationMs stays null
            }
        }

        return Output.builder()
            .executionId(execId)
            .status(status)
            .result(result)
            .startTime(startTime)
            .endTime(endTime)
            .totalDurationMs(totalDurationMs)
            .build();
    }

    @Builder
    @Getter
    public static class Output implements io.kestra.core.models.tasks.Output {
        @Schema(title = "Execution ID", description = "The ID of the Mistral workflow execution.")
        private final String executionId;

        @Schema(title = "Status", description = "Terminal status of the execution (e.g. COMPLETED, FAILED, CANCELED).")
        private final String status;

        @Schema(title = "Result", description = "JSON-serialized result payload returned by the workflow on successful completion.")
        private final String result;

        @Schema(title = "Start time", description = "ISO-8601 timestamp when the execution started.")
        private final String startTime;

        @Schema(title = "End time", description = "ISO-8601 timestamp when the execution ended.")
        private final String endTime;

        @Schema(title = "Total duration (ms)", description = "Wall-clock duration in milliseconds from start to end.")
        private final Long totalDurationMs;
    }
}
